project:
  type: book
  output-dir: docs

book:
  title: "COMP/STAT112 Notebook"
  author: "Owen Lindstrom"
  date: today
  reader-mode: true
  page-navigation: true
  back-to-top-navigation: true
  bread-crumbs: true
  
  
  sidebar:
    title: "Owen Lindstrom"
    collapse-level: 2
    style: "docked"
    pinned: true
    search: true
  
  
  chapters:
    - index.qmd

    - part: "Best Work"
      chapters: 
      - bw/bw-uni.qmd
      - bw/bw-bi.qmd
      - bw/bw-tri.qmd
      - bw/bw-quad.qmd
      - bw/bw-spatial.qmd

    - part: "In-class Activities"
      chapters: 
      - ica/ica-uni.qmd
      - ica/ica-bi.qmd
      - ica/ica-multi.qmd
      - ica/ica-spatial.qmd
      
    - part: "Solo Project"
      chapters:
      - bw/SoloProject.qmd
      
    - part: "Exams"
      chapters: 
      - ica/Exam1.qmd
      - ica/Exam2.qmd

format:
  html:
    theme:
      light: flatly
      dark: darkly
    toc: true
    toc-depth: 3
    link-external-newwindow: true
    css: style/custom.css
    code-copy: true
    code-link: true
    code-line-numbers: true
    code-tools: true
    echo: false
    warning: false
    message: false
    include-code: false

execute:
  cache: false
  freeze: false

editor: 
  markdown:
    wrap: sentence # Forces each sentence to be on its own line in source markdown, however, it doesn't affect how it is rendered
